apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jr-prod-rb
  namespace: production
subjects:
  - kind: Group
    name: junior
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io

  # Production namespace'indeki junior grubuna view cluster rolünü verir. view ile sadece okuma hakkı verilir.