apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jr-test-rb
  namespace: test
subjects:
  - kind: Group
    name: junior
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io

# Test namespace'indeki junior grubuna edit cluster rolünü verir. edit ile okuma, listeleme, yaratma... gibi hakları verir.
