apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sr-cluster-rb
subjects:
  - kind: Group
    name: senior
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io

# Senior grubu için cluster'ın geri kalanında sadece görüntülenme yetkisi verir.
