apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sr-prod-rb
  namespace: production
subjects:
  - kind: Group
    name: senior
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io

# Production namespace'indeki senior grubuna edit cluster rolünü verir. edit ile okuma, listeleme, yaratma... gibi hakları verir.
